/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Timer.h"
#include "isr_motor.h"
#include "LED_aliases.h"
#include "LED.h"
#include "Direction_1_1_aliases.h"
#include "Direction_1_1.h"
#include "Direction_1_2_aliases.h"
#include "Direction_1_2.h"
#include "PWM_1.h"
#include "PWM_motor_1_aliases.h"
#include "PWM_motor_1.h"
#include "QuadDec_1.h"
#include "DecoderPinA_1_aliases.h"
#include "DecoderPinA_1.h"
#include "DecoderPinB_1_aliases.h"
#include "DecoderPinB_1.h"
#include "QuadDec_2.h"
#include "DecoderPinA_2_aliases.h"
#include "DecoderPinA_2.h"
#include "DecoderPinB_2_aliases.h"
#include "DecoderPinB_2.h"
#include "PWM_2.h"
#include "PWM_motor_2_aliases.h"
#include "PWM_motor_2.h"
#include "UART.h"
#include "isr_1.h"
#include "Direction_2_1_aliases.h"
#include "Direction_2_1.h"
#include "Direction_2_2_aliases.h"
#include "Direction_2_2.h"
#include "QuadDec_1_Cnt16.h"
#include "QuadDec_2_Cnt16.h"
#include "UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

